AWSTemplateFormatVersion: "2010-09-09"
Description: "(SA0020) - filling-in-missing-values permissions stack"
Parameters:
  SolutionPrefix:
    Type: String
  S3BucketName:
    Type: String
  SolutionsS3BucketNamePrefix: 
    Type: String
  TestOutputsS3Bucket:
    Type: String
  RootStackId:
    Type: String

Conditions:
    AddTestBucketPermissions: !Not [!Equals [!Ref TestOutputsS3Bucket, ""]]

Resources:
  SageMakerIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${SolutionPrefix}-${AWS::Region}-nb-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sagemaker.amazonaws.com
            Action:
            - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - 'sts:AssumeRole'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Using explicit name to restrict permissions
  SageMakerIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${SolutionPrefix}-nb-instance-policy"
      Roles:
        - !Ref SageMakerIAMRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - sagemaker:CreateAutoMLJob
          - sagemaker:DescribeAutoMLJob
          Resource:
          - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*"
        - Effect: Allow
          Action:
          - sagemaker:CreateTrainingJob
          - sagemaker:DescribeTrainingJob
          - sagemaker:CreateProcessingJob
          - sagemaker:DescribeProcessingJob
          - sagemaker:CreateModel
          - sagemaker:DescribeEndpointConfig
          - sagemaker:DescribeEndpoint
          - sagemaker:CreateEndpointConfig
          - sagemaker:CreateEndpoint
          - sagemaker:DeleteEndpointConfig
          - sagemaker:DeleteEndpoint
          - sagemaker:DeleteModel
          - sagemaker:InvokeEndpoint
          Resource:
          - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*"
        - Effect: Allow
          Action:
          - cloudwatch:GetMetricData
          - cloudwatch:GetMetricStatistics
          - cloudwatch:ListMetrics
          - cloudwatch:PutMetricData
          Resource:
          - !Sub "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:*"
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:DescribeLogStreams
          - logs:GetLogEvents
          - logs:PutLogEvents
          Resource:
          - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/sagemaker/*"
          - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
        - Effect: Allow
          Action:
          - iam:PassRole
          Resource:
          - !GetAtt SageMakerIAMRole.Arn
          Condition:
            StringEquals:
              iam:PassedToService: sagemaker.amazonaws.com
        - Effect: Allow
          Action:
          - iam:GetRole
          Resource:
          - !GetAtt SageMakerIAMRole.Arn
        - Effect: Allow
          Action:
            - ecr:GetAuthorizationToken
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - ecr:BatchCheckLayerAvailability
          Resource:
            - "*"
        - Effect: Allow
          Action:
          - s3:ListBucket
          - s3:GetObject
          - s3:PutObject
          - s3:DeleteObject
          - s3:GetBucketLocation
          Resource:
            - !Sub "arn:aws:s3:::${S3BucketName}"
            - !Sub "arn:aws:s3:::${S3BucketName}/*"
        - Effect: Allow
          Action:
          - s3:ListBucket
          - s3:GetObject
          Resource:
          - !Sub "arn:aws:s3:::${SolutionsS3BucketNamePrefix}-${AWS::Region}"
          - !Sub "arn:aws:s3:::${SolutionsS3BucketNamePrefix}-${AWS::Region}/*"
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource:
          - !Sub "arn:aws:lambda:::function:*"
        # For CI Testing
        - Effect: Allow
          Action:
          - s3:AbortMultipartUpload
          - s3:GetObject
          - s3:PutObject
          - s3:DeleteObject
          - s3:ListBucket
          - s3:DeleteBucket
          - s3:GetBucketLocation
          - s3:ListBucketMultipartUploads
          Resource:
          # Update.
          - !Sub "arn:aws:s3:::*"
          - !Sub "arn:aws:s3:::*/*"
        # For CI Testing.
        - Effect: Allow
          Action:
          - cloudformation:DescribeStacks
          Resource:
          # Update.
          - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*/*"


    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: ECR GetAuthorizationToken is non resource-specific action

Outputs:
  SageMakerRoleArn:
    Description: "SageMaker Execution Role for the solution"
    Value: !GetAtt SageMakerIAMRole.Arn
